### ISSUE TITLE
question about B-MoCA environments

### ISSUE THREAD

**Issue by xuyifan-0731** [gimme1dollar/b-moca#1]
Hi! Thanks for your impressive work. When I use follow command to build B-MoCA environments, 
```
mkdir logs
bash install.sh
```
there are errors:

```
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 14/14 [00:01<00:00,  9.00it/s]
[=======================================] 100% Fetch remote repository...       
Error: Package path is not valid. Valid system image paths are:
null
pixel_3_train_00 avd created


avd pixel_3 created
INFO    | Android emulator version 33.1.24.0 (build_id 11237101) (CL:N/A)
ERROR   | Unknown AVD name [pixel_3_train_00], use -list-avds to see valid list.
ERROR   | ANDROID_AVD_HOME is defined but there is no file pixel_3_train_00.ini in $ANDROID_AVD_HOME
ERROR   | (Note: Directories are searched in the order $ANDROID_AVD_HOME, $ANDROID_SDK_HOME/avd and $HOME/.android/avd)
```

My installation process got stuck with the above error and did not continue.

My computer is Mac M2, and I used Android Studio and AVD before on my computer. (but there is no avd named pixel_3_train_00 before), and I use python environment bmoca within your repo. 

I have set $ANDROID_AVD_HOME, $ANDROID_SDK_HOME and $HOME as:
```
(bmoca) UserName@UserNamedeMacBook-Pro b-moca % echo $ANDROID_SDK_HOME                                                            
/Users/UserName/Documents/android_sdk/cmdline-tools/latest/bin
(bmoca) UserName@UserNamedeMacBook-Pro b-moca % echo $ANDROID_AVD_HOME                                                            
/Users/UserName/.android/avd
(bmoca) UserName@UserNamedeMacBook-Pro b-moca % echo $HOME             
/Users/UserName
```

**Comment by xuyifan-0731** [comment]
This issue might help:
https://github.com/NativeScript/NativeScript/issues/5667

I use this command and success to build avd:

$ cd $ANDROID_HOME/tools/bin

$ ./sdkmanager "system-images;android-25;google_apis;x86"

$ ./sdkmanager --licenses

(I had to accept all licenses)

Maybe this should add to build pipeline

**Comment by gimme1dollar** [comment]
Thanks for pointing this out!
This has already been guided to follow https://www.notion.so/Android-Studio-Setup-7c0fe37c623e46c8a89b6c24813255a4 for installing Android emulators.

Especially, note that the instruction for reproducing environments in B-MoCA is as bellow:
`$ ./sdkmanager "system-images;android-29;google_apis;x86_64" `
(Different android version can result in subtle differences in icon images or default wallpapers)

**Comment by gimme1dollar** [comment]
Thanks for pointing this out!
Installing Android emulators has been guided to follow https://www.notion.so/Android-Studio-Setup-7c0fe37c623e46c8a89b6c24813255a4 

Especially, note that the instruction for reproducing environments in B-MoCA is as bellow:
`$ ./sdkmanager "system-images;android-29;google_apis;x86_64" `
(Different android version can result in subtle differences in icon images or default wallpapers)

**Comment by jylee425** [comment]
Thanks for pointing this out!
Installing Android emulators has been guided to follow https://www.notion.so/Android-Studio-Setup-7c0fe37c623e46c8a89b6c24813255a4

Especially, note that the instruction for reproducing environments in B-MoCA is as bellow:
$ ./sdkmanager "system-images;android-29;google_apis;x86_64" 
(Different android version can result in subtle differences in icon images or default wallpapers)
